"""Write .gcloudignore and .dockerignore so the build context holds the code, the
baselines and ONLY the registered model version (latest.json), not the lake,
the FastF1 cache, node_modules or older model runs.

    python3 scripts/deploy_ignore.py
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
latest = json.loads((ROOT / "data/artifacts/models/latest.json").read_text())["version"]

rules = f"""# generated by scripts/deploy_ignore.py — do not edit by hand
.git/
.gitignore
.gcloudignore
.dockerignore
**/__pycache__/
**/.pytest_cache/
**/.ruff_cache/
backend/.venv/
backend/data/
backend/tests/
frontend/node_modules/
frontend/.next/
frontend/out/
frontend/tsconfig.tsbuildinfo
docs/
data/cache/
data/bronze/
data/silver/
data/gold/
data/logs/
data/artifacts/models/v*/
!data/artifacts/models/{latest}/
.env
.env.local
*.md
!README.md
"""
for name in (".gcloudignore", ".dockerignore"):
    (ROOT / name).write_text(rules)
print(f"build context: code + baselines + model {latest}")
